version: "3"
services:

  v2ray:
    image: v2fly/v2fly-core
    network_mode: host
    environment:
      - V2RAY_VMESS_AEAD_FORCED=false
    volumes:
      - ./data/v2ray-config/config2.json:/etc/v2ray/config.json
    restart: always