version: "3"
services:

  v2ray:
    image: v2fly/v2fly-core
    network_mode: host
    volumes:
      - ./data/v2ray-config:/etc/v2ray
    restart: always

  nginx:
    image: nginx:1.18-alpine
    network_mode: host
    volumes:
      - ./data/nginx-config:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - v2ray
    restart: always

  certbot:
    image: certbot/certbot
    network_mode: host
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always